name: cric_auction
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Theming
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_colorpicker: ^1.1.0
  nb_utils: ^7.1.4
  html: ^0.15.5
  lottie: ^3.3.1
  cached_network_image: ^3.4.1

  # File & Storage Management
  path_provider: ^2.1.5
  get_storage: ^2.1.1

  # Date & Localization
  intl: ^0.20.2

  # Image & Media Handling
  image_picker: ^1.1.2
  photo_view: ^0.15.0

  # Firebase Services
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0

  # Networking & API
  http_parser: ^4.1.2

  # Permissions
  permission_handler: ^11.4.0

  # State Management
  get: ^4.7.2

  # Chart
  fl_chart: ^0.71.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/
    - assets/icons/
    - assets/logos/
    - assets/lotties/
    - assets/images/
    - assets/font/

  uses-material-design: true 